# Generated by Django 3.1.2 on 2021-01-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_ovimot_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovimot',
            name='author',
        ),
    ]
